# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/semantic_kitti_implementations',
                'doc_host': 'https://AIR-UFG.github.io',
                'git_url': 'https://github.com/AIR-UFG/semantic_kitti_implementations',
                'lib_path': 'semantic_kitti_implementations'},
  'syms': { 'semantic_kitti_implementations.data': { 'semantic_kitti_implementations.data.SemanticDataset': ( 'data.html#semanticdataset',
                                                                                                              'semantic_kitti_implementations/data.py'),
                                                     'semantic_kitti_implementations.data.SemanticDataset.__getitem__': ( 'data.html#semanticdataset.__getitem__',
                                                                                                                          'semantic_kitti_implementations/data.py'),
                                                     'semantic_kitti_implementations.data.SemanticDataset.__init__': ( 'data.html#semanticdataset.__init__',
                                                                                                                       'semantic_kitti_implementations/data.py'),
                                                     'semantic_kitti_implementations.data.SemanticDataset.__len__': ( 'data.html#semanticdataset.__len__',
                                                                                                                      'semantic_kitti_implementations/data.py'),
                                                     'semantic_kitti_implementations.data.remap_segmentation_masks': ( 'data.html#remap_segmentation_masks',
                                                                                                                       'semantic_kitti_implementations/data.py')}}}
