# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/semantic_kitti_implementations',
                'doc_host': 'https://AIR-UFG.github.io',
                'git_url': 'https://github.com/AIR-UFG/semantic_kitti_implementations',
                'lib_path': 'semantic_kitti_implementations'},
  'syms': { 'semantic_kitti_implementations.core': { 'semantic_kitti_implementations.core.foo': ( 'core.html#foo',
                                                                                                  'semantic_kitti_implementations/core.py')}}}
